variable "environment_name" {
  type = string
}

variable "vpc_id" {
  type = string
}

variable "private_subnet_ids" {
  type = list(string)
}

variable "security_group_id" {
  description = "RDS's own security group (attached to the DB instance's ENI)."
  type        = string
}

variable "ecs_security_group_id" {
  description = <<-EOT
    ECS tasks' security group — attached to the one-off bootstrap task's ENI,
    NOT to the RDS instance. RDS's own security group only allows ingress
    FROM this one; a task can't reach RDS while wearing RDS's security group
    instead of the group RDS's ingress rule actually trusts.
  EOT
  type = string
}

variable "instance_class" {
  type = string
}

variable "allocated_storage_gb" {
  type = number
}

variable "multi_az" {
  type = bool
}

variable "backup_retention_days" {
  type = number
}

variable "deletion_protection" {
  type = bool
}

variable "level1_db_name" {
  description = "Database name created by RDS at instance creation (matches docker-compose's POSTGRES_DB)."
  type        = string
  default     = "cyber_odyssey"
}

variable "portal_db_name" {
  description = "Second database, created after the instance exists (matches docker-compose's PORTAL_DB)."
  type        = string
  default     = "odyssey_portal"
}

variable "master_username" {
  type    = string
  default = "odyssey"
}

variable "master_password" {
  description = "RDS master password. Generated by modules/secrets, passed in here so there is one source of truth."
  type        = string
  sensitive   = true
}

variable "master_password_secret_arn" {
  description = "Secrets Manager ARN holding the same password, for the bootstrap task to read at runtime instead of embedding it in a task definition."
  type        = string
}

variable "ecs_cluster_arn" {
  description = "Cluster the one-off bootstrap task runs in."
  type        = string
}

variable "aws_region" {
  type = string
}

